---
- name:         Get list of Identity endpoints.
  register:     openstack_identity_endpoints
  changed_when: no
  command:      openstack endpoint list -f value -c Interface --service identity

- name:    Create Identity endpoints.
  command: 'openstack endpoint create --region {{ region }} identity {{ item.key }} {{ item.value }}'
  when:    '"{{ item.key }}" not in openstack_identity_endpoints.stdout'
  with_dict:
    public:   'http://{{ host }}:5000/v3'
    internal: 'http://{{ host }}:5000/v3'
    admin:    'http://{{ host }}:35357/v3'
